/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApexChart: typeof import('./src/components/ApexChart.vue')['default']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-next/components/BCard')['BCardFooter']
    BCardHeader: typeof import('bootstrap-vue-next/components/BCard')['BCardHeader']
    BCardTitle: typeof import('bootstrap-vue-next/components/BCard')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BOffcanvas: typeof import('bootstrap-vue-next/components/BOffcanvas')['BOffcanvas']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTableSimple: typeof import('bootstrap-vue-next/components/BTable')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next/components/BTable')['BTbody']
    BTd: typeof import('bootstrap-vue-next/components/BTable')['BTd']
    BTh: typeof import('bootstrap-vue-next/components/BTable')['BTh']
    BThead: typeof import('bootstrap-vue-next/components/BTable')['BThead']
    BTr: typeof import('bootstrap-vue-next/components/BTable')['BTr']
    ChoicesInput: typeof import('./src/components/ChoicesInput.vue')['default']
    ChoicesSelect: typeof import('./src/components/ChoicesSelect.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    FlatPicker: typeof import('./src/components/FlatPicker.vue')['default']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    FormSelect: typeof import('./src/components/form/FormSelect.vue')['default']
    FormTextarea: typeof import('./src/components/form/FormTextarea.vue')['default']
    GridJsTable: typeof import('./src/components/GridJsTable.vue')['default']
    InputMask: typeof import('./src/components/InputMask.vue')['default']
    JsVectorMap: typeof import('./src/components/JsVectorMap.vue')['default']
    LogoBox: typeof import('./src/components/LogoBox.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UICard: typeof import('./src/components/UICard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-next/directives/BToggle')['vBToggle']
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
